package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.blocks.AlarmBlock;
import net.geforcemods.securitycraft.blocks.BlockPocketManagerBlock;
import net.geforcemods.securitycraft.blocks.BlockPocketWallBlock;
import net.geforcemods.securitycraft.blocks.DisplayCaseBlock;
import net.geforcemods.securitycraft.blocks.ElectrifiedIronFenceBlock;
import net.geforcemods.securitycraft.blocks.ElectrifiedIronFenceGateBlock;

import net.geforcemods.securitycraft.blocks.FloorTrapBlock;
import net.geforcemods.securitycraft.blocks.FrameBlock;
import net.geforcemods.securitycraft.blocks.InventoryScannerBlock;
import net.geforcemods.securitycraft.blocks.InventoryScannerFieldBlock;
import net.geforcemods.securitycraft.blocks.KeyPanelFloorCeilingBlock;
import net.geforcemods.securitycraft.blocks.KeyPanelWallBlock;
import net.geforcemods.securitycraft.blocks.KeycardLockFloorCeilingBlock;
import net.geforcemods.securitycraft.blocks.KeycardLockWallBlock;
import net.geforcemods.securitycraft.blocks.KeycardReaderBlock;
import net.geforcemods.securitycraft.blocks.KeypadBlock;
import net.geforcemods.securitycraft.blocks.KeypadChestBlock;
import net.geforcemods.securitycraft.blocks.KeypadDoorBlock;
import net.geforcemods.securitycraft.blocks.KeypadFurnaceBlock;
import net.geforcemods.securitycraft.blocks.LaserBlock;
import net.geforcemods.securitycraft.blocks.LaserFieldBlock;
import net.geforcemods.securitycraft.blocks.MotionActivatedLightBlock;
import net.geforcemods.securitycraft.blocks.OldLitAlarmBlock;
import net.geforcemods.securitycraft.blocks.PanicButtonBlock;
import net.geforcemods.securitycraft.blocks.PortableRadarBlock;
import net.geforcemods.securitycraft.blocks.ProjectorBlock;
import net.geforcemods.securitycraft.blocks.ProtectoBlock;
import net.geforcemods.securitycraft.blocks.RetinalScannerBlock;
import net.geforcemods.securitycraft.blocks.RiftStabilizerBlock;
import net.geforcemods.securitycraft.blocks.ScannerDoorBlock;
import net.geforcemods.securitycraft.blocks.SecretStandingSignBlock;
import net.geforcemods.securitycraft.blocks.SecretWallSignBlock;
import net.geforcemods.securitycraft.blocks.SecureRedstoneInterfaceBlock;
import net.geforcemods.securitycraft.blocks.SecurityCameraBlock;
import net.geforcemods.securitycraft.blocks.SonicSecuritySystemBlock;
import net.geforcemods.securitycraft.blocks.UsernameLoggerBlock;
import net.geforcemods.securitycraft.items.AdminToolItem;
import net.geforcemods.securitycraft.items.BriefcaseItem;
import net.geforcemods.securitycraft.items.CameraMonitorItem;
import net.geforcemods.securitycraft.items.CodebreakerItem;
import net.geforcemods.securitycraft.items.FloorCeilingWallBlockItem;
import net.geforcemods.securitycraft.items.KeyPanelItem;
import net.geforcemods.securitycraft.items.KeycardHolderItem;
import net.geforcemods.securitycraft.items.KeycardItem;
import net.geforcemods.securitycraft.items.LensItem;
import net.geforcemods.securitycraft.items.ModuleItem;
import net.geforcemods.securitycraft.items.PortableTunePlayerItem;
import net.geforcemods.securitycraft.items.SCManualItem;
import net.geforcemods.securitycraft.items.SecretSignItem;
import net.geforcemods.securitycraft.items.SonicSecuritySystemItem;
import net.geforcemods.securitycraft.items.SpecialDoorItem;
import net.geforcemods.securitycraft.items.TaserItem;
import net.geforcemods.securitycraft.items.UniversalBlockRemoverItem;
import net.geforcemods.securitycraft.items.UniversalKeyChangerItem;
import net.geforcemods.securitycraft.items.UniversalOwnerChangerItem;
import net.geforcemods.securitycraft.items.WireCuttersItem;
import net.geforcemods.securitycraft.misc.ModuleType;
import net.geforcemods.securitycraft.screen.ScreenHandler.Screens;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;

public class SetupHandler {
	private SetupHandler() {}

	public static void init() {
		//blocks
		SCContent.laserBlock = new LaserBlock(Material.ROCK).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("laser_block").setTranslationKey("securitycraft:laserBlock");
		SCContent.laserField = new LaserFieldBlock(Material.ROCK).setBlockUnbreakable().setRegistryName("laser").setTranslationKey("securitycraft:laserField");
		SCContent.keypad = new KeypadBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("keypad").setTranslationKey("securitycraft:keypad");
		SCContent.retinalScanner = new RetinalScannerBlock(Material.ROCK).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("retinal_scanner").setTranslationKey("securitycraft:retinalScanner");
		SCContent.keycardReader = new KeycardReaderBlock(Material.ROCK).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("keycard_reader").setTranslationKey("securitycraft:keycardReader");
		SCContent.inventoryScanner = new InventoryScannerBlock(Material.ROCK).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("inventory_scanner").setTranslationKey("securitycraft:inventoryScanner");
		SCContent.inventoryScannerField = new InventoryScannerFieldBlock(Material.GLASS).setBlockUnbreakable().setRegistryName("inventory_scanner_field").setTranslationKey("securitycraft:inventoryScannerField");
		SCContent.portableRadar = new PortableRadarBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("portable_radar").setTranslationKey("securitycraft:portableRadar");
		SCContent.keypadChest = new KeypadChestBlock().setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("keypad_chest").setTranslationKey("securitycraft:keypadChest");
		SCContent.usernameLogger = new UsernameLoggerBlock(Material.ROCK).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("username_logger").setTranslationKey("securitycraft:usernameLogger");
		SCContent.alarm = new AlarmBlock(Material.IRON).setTickRandomly(true).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("alarm").setTranslationKey("securitycraft:alarm");
		SCContent.alarmLit = new OldLitAlarmBlock(Material.IRON).setTickRandomly(true).setRegistryName("alarm_lit").setTranslationKey("securitycraft:alarmLit");
		SCContent.electrifiedIronFenceGate = new ElectrifiedIronFenceGateBlock().setCreativeTab(SecurityCraft.DECORATION_TAB).setRegistryName("reinforced_fence_gate").setTranslationKey("securitycraft:reinforcedFenceGate");
		SCContent.panicButton = new PanicButtonBlock().setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("panic_button").setTranslationKey("securitycraft:panicButton");
		SCContent.frame = new FrameBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("keypad_frame").setTranslationKey("securitycraft:keypadFrame");
		SCContent.keypadFurnace = new KeypadFurnaceBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("keypad_furnace").setTranslationKey("securitycraft:keypadFurnace");
		SCContent.securityCamera = new SecurityCameraBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("security_camera").setTranslationKey("securitycraft:securityCamera");
		SCContent.electrifiedIronFence = new ElectrifiedIronFenceBlock(Material.IRON).setCreativeTab(SecurityCraft.DECORATION_TAB).setRegistryName("electrified_iron_fence").setTranslationKey("securitycraft:electrifiedIronFence");
		SCContent.protecto = new ProtectoBlock(Material.IRON).setLightLevel(0.5F).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("protecto").setTranslationKey("securitycraft:protecto");
		SCContent.scannerDoor = new ScannerDoorBlock(Material.IRON).setCreativeTab(SecurityCraft.DECORATION_TAB).setRegistryName("scanner_door").setTranslationKey("securitycraft:scannerDoor");
		SCContent.secretSignStanding = new SecretStandingSignBlock().setRegistryName("secret_sign_standing").setTranslationKey("securitycraft:secretSign");
		SCContent.secretSignWall = new SecretWallSignBlock().setRegistryName("secret_sign_wall").setTranslationKey("securitycraft:secretSign");
		SCContent.motionActivatedLight = new MotionActivatedLightBlock(Material.GLASS).setRegistryName("motion_activated_light").setTranslationKey("securitycraft:motionActivatedLight").setCreativeTab(SecurityCraft.TECHNICAL_TAB);
		SCContent.blockPocketWall = new BlockPocketWallBlock().setCreativeTab(SecurityCraft.DECORATION_TAB).setRegistryName("block_pocket_wall").setTranslationKey("securitycraft:blockPocketWall");
		SCContent.blockPocketManager = new BlockPocketManagerBlock().setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("block_pocket_manager").setTranslationKey("securitycraft:blockPocketManager");
		SCContent.projector = new ProjectorBlock().setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("projector").setTranslationKey("securitycraft:projector");
		SCContent.keypadDoor = new KeypadDoorBlock(Material.IRON).setCreativeTab(SecurityCraft.DECORATION_TAB).setRegistryName("keypad_door").setTranslationKey("securitycraft:keypad_door");
		SCContent.keyPanelFloorCeilingBlock = new KeyPanelFloorCeilingBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("floor_ceiling_key_panel").setTranslationKey("securitycraft:key_panel");
		SCContent.keyPanelWallBlock = new KeyPanelWallBlock(Material.IRON).setRegistryName("wall_key_panel").setTranslationKey("securitycraft:key_panel");
		SCContent.sonicSecuritySystem = new SonicSecuritySystemBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("sonic_security_system").setTranslationKey("securitycraft:sonic_security_system");
		SCContent.riftStabilizer = new RiftStabilizerBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("rift_stabilizer").setTranslationKey("securitycraft:rift_stabilizer");
		SCContent.displayCase = new DisplayCaseBlock(Material.IRON).setCreativeTab(SecurityCraft.DECORATION_TAB).setRegistryName("display_case").setTranslationKey("securitycraft:display_case");
		SCContent.floorTrap = new FloorTrapBlock(Material.IRON).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setHardness(-1.0F).setRegistryName("floor_trap").setTranslationKey("securitycraft:floor_trap");
		SCContent.keycardLockFloorCeilingBlock = new KeycardLockFloorCeilingBlock(Material.ROCK).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("floor_ceiling_keycard_lock").setTranslationKey("securitycraft:keycard_lock");
		SCContent.keycardLockWallBlock = new KeycardLockWallBlock(Material.ROCK).setRegistryName("wall_keycard_lock").setTranslationKey("securitycraft:keycard_lock");
		SCContent.secureRedstoneInterface = new SecureRedstoneInterfaceBlock(Material.ROCK).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("secure_redstone_interface").setTranslationKey("securitycraft:secure_redstone_interface");
		//items
		SCContent.codebreaker = new CodebreakerItem().setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("codebreaker").setTranslationKey("securitycraft:codebreaker");
		SCContent.keycardLvl1 = new KeycardItem(0).setRegistryName("keycard_lv1").setTranslationKey("securitycraft:keycardLV1");
		SCContent.keycardLvl2 = new KeycardItem(1).setRegistryName("keycard_lv2").setTranslationKey("securitycraft:keycardLV2");
		SCContent.keycardLvl3 = new KeycardItem(2).setRegistryName("keycard_lv3").setTranslationKey("securitycraft:keycardLV3");
		SCContent.keycardLvl4 = new KeycardItem(3).setRegistryName("keycard_lv4").setTranslationKey("securitycraft:keycardLV4");
		SCContent.keycardLvl5 = new KeycardItem(4).setRegistryName("keycard_lv5").setTranslationKey("securitycraft:keycardLV5");
		SCContent.limitedUseKeycard = new KeycardItem(-1).setRegistryName("limited_use_keycard").setTranslationKey("securitycraft:limitedUseKeycard");
		SCContent.universalBlockRemover = new UniversalBlockRemoverItem().setMaxStackSize(1).setMaxDamage(476).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("universal_block_remover").setTranslationKey("securitycraft:universalBlockRemover");
		SCContent.universalBlockModifier = new Item().setMaxStackSize(1).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("universal_block_modifier").setTranslationKey("securitycraft:universalBlockModifier");
		SCContent.redstoneModule = (ModuleItem) new ModuleItem(ModuleType.REDSTONE, false).setRegistryName("redstone_module").setTranslationKey("securitycraft:redstoneModule");
		SCContent.allowlistModule = (ModuleItem) new ModuleItem(ModuleType.ALLOWLIST, true, true, Screens.MODULES.ordinal()).setRegistryName("whitelist_module").setTranslationKey("securitycraft:whitelistModule");
		SCContent.denylistModule = (ModuleItem) new ModuleItem(ModuleType.DENYLIST, true, true, Screens.MODULES.ordinal()).setRegistryName("blacklist_module").setTranslationKey("securitycraft:blacklistModule");
		SCContent.harmingModule = (ModuleItem) new ModuleItem(ModuleType.HARMING, false).setRegistryName("harming_module").setTranslationKey("securitycraft:harmingModule");
		SCContent.smartModule = (ModuleItem) new ModuleItem(ModuleType.SMART, false).setRegistryName("smart_module").setTranslationKey("securitycraft:smartModule");
		SCContent.storageModule = (ModuleItem) new ModuleItem(ModuleType.STORAGE, false).setRegistryName("storage_module").setTranslationKey("securitycraft:storageModule");
		SCContent.disguiseModule = (ModuleItem) new ModuleItem(ModuleType.DISGUISE, false, true, Screens.DISGUISE_MODULE.ordinal()).setRegistryName("disguise_module").setTranslationKey("securitycraft:disguiseModule");
		SCContent.speedModule = (ModuleItem) new ModuleItem(ModuleType.SPEED, false).setRegistryName("speed_module").setTranslationKey("securitycraft:speed_module");
		SCContent.wireCutters = new WireCuttersItem().setMaxStackSize(1).setMaxDamage(476).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("wire_cutters").setTranslationKey("securitycraft:wireCutters");
		SCContent.keyPanel = new KeyPanelItem().setRegistryName("keypad_item");
		SCContent.adminTool = new AdminToolItem().setMaxStackSize(1).setRegistryName("admin_tool").setTranslationKey("securitycraft:adminTool");
		SCContent.cameraMonitor = new CameraMonitorItem().setMaxStackSize(1).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("camera_monitor").setTranslationKey("securitycraft:cameraMonitor");
		SCContent.scManual = new SCManualItem().setMaxStackSize(1).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("sc_manual").setTranslationKey("securitycraft:scManual");
		SCContent.taser = new TaserItem(false).setMaxStackSize(1).setRegistryName("taser").setTranslationKey("securitycraft:taser");
		SCContent.taserPowered = new TaserItem(true).setMaxStackSize(1).setRegistryName("taser_powered").setTranslationKey("securitycraft:taser");
		SCContent.universalOwnerChanger = new UniversalOwnerChangerItem().setMaxStackSize(1).setMaxDamage(48).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("universal_owner_changer").setTranslationKey("securitycraft:universalOwnerChanger");
		SCContent.briefcase = new BriefcaseItem().setMaxStackSize(1).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("briefcase").setTranslationKey("securitycraft:briefcase");
		SCContent.universalKeyChanger = new UniversalKeyChangerItem().setMaxStackSize(1).setCreativeTab(SecurityCraft.TECHNICAL_TAB).setRegistryName("universal_key_changer").setTranslationKey("securitycraft:universalKeyChanger");
		SCContent.scannerDoorItem = new SpecialDoorItem(SCContent.scannerDoor).setRegistryName("scanner_door_item").setTranslationKey("securitycraft:scannerDoorItem").setCreativeTab(SecurityCraft.DECORATION_TAB);
		SCContent.secretSignItem = new SecretSignItem().setRegistryName("secret_sign_item").setTranslationKey("securitycraft:secretSignItem").setCreativeTab(SecurityCraft.DECORATION_TAB);
		SCContent.keypadDoorItem = new SpecialDoorItem(SCContent.keypadDoor).setRegistryName("keypad_door_item").setTranslationKey("securitycraft:keypad_door_item").setCreativeTab(SecurityCraft.DECORATION_TAB);
		SCContent.sonicSecuritySystemItem = new SonicSecuritySystemItem().setTranslationKey("securitycraft:sonic_security_system").setCreativeTab(SecurityCraft.TECHNICAL_TAB);
		SCContent.portableTunePlayer = new PortableTunePlayerItem().setRegistryName("portable_tune_player").setTranslationKey("securitycraft:portable_tune_player").setCreativeTab(SecurityCraft.TECHNICAL_TAB);
		SCContent.keycardHolder = new KeycardHolderItem().setRegistryName("keycard_holder").setTranslationKey("securitycraft:keycard_holder").setCreativeTab(SecurityCraft.TECHNICAL_TAB);
		SCContent.lens = (LensItem) new LensItem().setRegistryName("lens").setTranslationKey("securitycraft:lens").setCreativeTab(SecurityCraft.TECHNICAL_TAB);
		SCContent.keycardLock = new FloorCeilingWallBlockItem(SCContent.keycardLockFloorCeilingBlock, SCContent.keycardLockWallBlock).setRegistryName("keycard_lock");
	}
}
